teamE/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :gourmet_posts do
    resources :likes, only: [:create]
    delete :likes, to: 'likes#destroy'
  end
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  resources :users
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

teamE/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  name            :string(255)      not null
#  password_digest :string(255)      not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  login_id        :string(30)       not null
#
class User < ApplicationRecord
  has_many :posts
  has_many :likes

  validates :name, presence: true
  validates :login_id, presence: true, uniqueness: true, length: {maximum: 30}
  has_secure_password(validations: false)

  validate do |record|
    record.errors.add(:password, :blank) if record.password_digest.blank?
  end

  validates :password, format: { with: /\A[a-zA-Z0-9]+\z/, message: "は半角英数字のみが使用できます" }
  validates_length_of :password, maximum: ActiveModel::SecurePassword::MAX_PASSWORD_LENGTH_ALLOWED
  validates_confirmation_of :password, allow_blank: true

  validates :password_confirmation, presence: true
end

teamE/app/controllers/users_controller.rb
class UsersController < ApplicationController
  include SessionsConcern

  before_action :login_required, except: %i[new create]
  before_action :set_user, only: %i[show]
  before_action :correct_user, only: %i[show]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      flash[:notice] = "新規登録が完了しました。"
      redirect_to gourmet_posts_path
    else
      unless @user.errors.full_messages.any? {|e| e.include?("を入力してください")}
        flash.now[:danger] = '正しい情報を入力してください。'
      end
      render 'new'
    end
  end

  def show; end

  private

  def user_params
    params.require(:user).permit(:name, :login_id, :password, :password_confirmation)
  end

  def set_user
    @user = User.find_by(id: params[:id])
  end

  def correct_user
    unless current_user == @user
      flash[:danger] = 'アクセスが拒否されました。'
      redirect_to user_path(current_user)
    end
  end
end

teamE/app/views/users/new.html.erb
<div class="card mt-3 w-50 mx-auto">
  <div class="card-body">
    <%= form_with model: @user, url: signup_path, local: true  do |form| %>
      <div class='mb-3'>
        <%= form.text_field :name, class: "w-100", placeholder: "名前" %>
      </div>
      <div class='mb-3'>
        <%= form.text_field :login_id, class: "w-100", placeholder: "ログインID" %>
      </div>
      <div class='mb-3'>
        <%= form.password_field :password, class: "w-100", placeholder: "パスワード" %>
      </div>
      <div class='mb-3'>
        <%= form.password_field :password_confirmation, class: "w-100", placeholder: "パスワード(確認)" %>
      </div>
      <div class="d-flex justify-content-between mb-3">
        <div class="mt-3 p-2 bd-highlight"><%= link_to "ログイン", login_path, class: "" %></div>
        <div class="ml-auto p-2 bd-highlight"><%= form.submit class: 'btn btn-primary' %></div>
      </div>
    <% end %>
  </div>
</div>

teamE/app/views/users/show.html.erb
<div class="row" style="margin-left: 0; margin-right: 0;">
  <div class="row" style="margin-left: 0; margin-right: 0;">
    <div class="card mt-2">
      <div class="card-body">
        <div>
          <p>ユーザー名: <%= @user.name %></p>
        </div>
        <div>
          <p>ログインID: <%= @user.login_id %></p>
        </div>
      </div>
    </div>
    <% @user.posts.with_attached_picture.order(updated_at: "DESC").includes([:picture_attachment]).each do |post| %>
      <% image_url = post.picture.presence || '/no_image.jpeg' %>
      <div class='col-md-4 p-1' style='margin-top: 10px; border: double thick; border-color: rgb(255, 102, 51 ,0.33);'>
        <div>
          <%= link_to image_url, "data-lightbox" => image_url do %>
            <%= image_tag image_url, style: 'width:100%;height: 400px;' %>
          <% end %>
        </div>
        <div class='post-infomation' style='display:flex; flex-direction:column;' >
          <div>
            <h5 class='float-start'><%= link_to post.title, gourmet_post_path(post), data: {"turbolinks" => false} %></h5>
          </div>
          <div class='post-create-information' style='display:flex; justify-content:space-between; position:relative; top: 0; left: 0;'>
            <div class='post-created_at'><p>投稿日: <%= post.created_at.strftime("%Y/%m/%d") %></p></div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>