teamE/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :gourmet_posts do
    resources :likes, only: [:create]
    delete :likes, to: 'likes#destroy'
  end
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  resources :users
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

teamE/app/views/layouts/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

teamE/app/views/layouts/_footer.html.erb
<% return if request.path_info == "/login" || request.path_info == "/signup" %>
<section class="mt-3 sticky-bottom">
  <% if !logged_in? %>
    <footer class="text-center text-white bg-primary">
      <div class="container p-1">
        <section class="mt-3">
          <p class="d-flex justify-content-center align-items-center">
            <%= link_to "ログイン", login_path, class: "btn btn-outline-success bg-white me-5" %>
            <%= link_to signup_path do %>
              <button type="button" class="btn btn-outline-light btn-rounded me-5">
                新規登録
              </button>
            <% end %>
          </p>
        </section>
      </div>
    </footer>
  <% end %>
</section>

teamE/app/views/layouts/_header.html.erb
<div class="sticky-top">
  <div id="carouselExampleCaptions" class="carousel slide border-primary border border-5" data-bs-ride="carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <%= link_to 'https://twitter.com/VarealMan', target: :_blank do %>
          <%= image_tag "/vareal_man_header.jpeg", class: "d-block w-100", alt: "...", height: '200' %>
        <% end %>
      </div>
      <div class="carousel-item">
        <%= link_to 'https://www.vareal.co.jp/', target: :_blank do %>
          <%= image_tag "https://www.vareal.co.jp/wp-content/uploads/2020/02/topvisual1.jpg", class: "d-block w-100", alt: "...", height: '200' %>
          <div class="carousel-caption d-none d-md-block">
            <h2 class="title rich_font_type3" data-label="V i r t u a l × R E A L"><span>Virtual × REAL</span></h2>
          </div>
        <% end %>
      </div>
      <div class="carousel-item">
        <%= link_to 'https://www.vareal.vn/en/', target: :_blank do %>
          <%= image_tag "https://www.vareal.vn/wp-content/uploads/2021/06/working_environment.jpg", class: "d-block w-100", alt: "...", height: '200' %>
          <div class="carousel-caption d-none d-md-block">
            <h2 class="title rich_font_type3" data-label="Together at Vareal Vietnam "><span>Together at Vareal Vietnam</span></h2>
          </div>
        <% end %>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
  <div class='d-flex flex-row-reverse'>
    <% if request.path_info != "/gourmet_posts/new" %>
      <%= link_to new_gourmet_post_path, style: "text-decoration: none;margin-right: 10px;", "data-bs-toggle": "tooltip", "data-bs-placement": "top", "data-bs-original-title": "投稿する", class: 'write-icon-link' do %>
        <i class="far fa-edit fa-2x write-icon" style='color:#ff6633' alt="投稿"></i>
      <% end %>
    <% end %>
    <a class="nav-link dropdown-toggle humberger-menu" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
      <i class="fas fa-bars fa-3x", style='color:#ff6633'></i>
    </a>
    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
      <% if logged_in? %>
        <li>
          <%= link_to logout_path(current_user), method: :delete, class: 'dropdown-item' do %>
            ログアウト
          <% end %>
        </li>
        <li>
          <%= link_to user_path(current_user), class: 'dropdown-item' do %>
            マイページ
          <% end %>
        </li>
      <% else %>
        <li>
          <%= link_to "/login", class: 'dropdown-item' do %>
            ログイン
          <% end %>
        </li>
        <li>
          <%= link_to "/signup", class: 'dropdown-item' do %>
            新規登録
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

teamE/app/views/layouts/_sidebar.html.erb
<div class="col-md-3 ">
  <div class="sidebar">
    <div class="sidebar-content" >
      <% @genres.each do |genre| %>
        <p><%= Post.human_attribute_name("genre.#{genre}") %></p>
        <p>
          <a href="#">TOKYO</a>
          <span></span>
          <a href="#">FUKUOKA</a>
          <span></span>
          <a href="#">OTHERS</a>
        </p>
      <% end %>
    </div>
  </div>
</div>

teamE/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_packs_with_chunks_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_packs_with_chunks_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_packs_with_chunks_tag 'gourmet_posts/preview' %>
    <%= javascript_packs_with_chunks_tag 'layouts/lightbox' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  </head>

  <body>
    <div class="container">
      <div class="row">
        <%= render 'layouts/header' %>
        <%= render 'layouts/flash_message' %>
        <%= yield %>
        <%= render 'layouts/footer' %>
      </div>
    </div>
  </body>
</html>