teamE/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :gourmet_posts do
    resources :likes, only: [:create]
    delete :likes, to: 'likes#destroy'
  end
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  resources :users
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

teamE/app/models/like.rb
# == Schema Information
#
# Table name: likes
#
#  id(ID)              :bigint           unsigned, not null, primary key
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  post_id(投稿ID)     :bigint           not null
#  user_id(ユーザーID) :bigint           not null
#
# Indexes
#
#  index_likes_on_post_id  (post_id)
#  index_likes_on_user_id  (user_id)
#  post_id                 (post_id,user_id) UNIQUE
#  user_id                 (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (post_id => posts.id)
#  fk_rails_...  (user_id => users.id)
#
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates_uniqueness_of :post_id, scope: :user_id
end

teamE/app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :login_required
  before_action :set_post, only: [:create, :destroy]

  def create
    like = @current_user.likes.new(post_id: params[:gourmet_post_id])
    like.save!
    render 'update'
  end

  def destroy
    like = @current_user.likes.find_by(post_id: params[:gourmet_post_id])
    like.destroy!
    render 'update'
  end

  private 

  def set_post
    @post = Post.find(params[:gourmet_post_id])
  end
end

teamE/app/views/likes/_like_btn.html.erb
<% # いいねボタン %>
<%= link_to gourmet_post_likes_path(@post), method: :delete, remote: true, style: (@liked ? "" : "display:none;"), "role": "button", "data-like-post-id": @post.id, "data-like-btn": "", "data-bs-toggle": "tooltip", "data-bs-placement": "bottom", "data-bs-original-title": "いいねを取り消し" do %>
  <i class="fas fa-heart text-primary"></i>
<% end %>
<%= link_to gourmet_post_likes_path(@post), method: :post, remote: true, style: (@liked ? "display:none;" : ""), "role": "button", "data-like-post-id": @post.id, "data-like-btn": "", "data-bs-toggle": "tooltip", "data-bs-placement": "bottom", "data-bs-original-title": "いいね" do %>
  <i class="far fa-heart text-primary"></i>
<% end %>

<script>
$(function() {
  // 多重送信対策
  $('[data-like-btn]').on('click', function(e) {
    const nowRequesting = $(this).data('now-requesting');
    if (nowRequesting) return false;
    const postId = $(this).data('like-post-id');
    $('[data-like-btn][data-like-post-id="'+postId+'"]').data('now-requesting', true);
  });
});
</script>

teamE/app/views/likes/_like_count.html.erb
<% # いいね数 %>
<span class="pe-1 text-primary" data-like-count data-like-post-id="<%= post.id %>">
  <%= number_to_human post.likes.count, format: '%n%u', units: {thousand: 'k'} %>
</span>

teamE/app/views/likes/_like_count_and_btn.html.erb
<% # いいね数 %>
<span class="pe-1 text-primary" data-like-count data-like-post-id="<%= @post.id %>">
    <%= number_to_human @post.likes.count, format: '%n%u', units: {thousand: 'k'} %>
</span>

<% # いいねボタン %>
<% is_liked = @current_user.likes.exists?(post_id: @post.id) # trueならいいね済み %>
<%= link_to gourmet_post_likes_path(@post), method: :delete, remote: true, style: (is_liked ? "" : "display:none;"), "role": "button", "data-like-post-id": @post.id, "data-like-btn": "", "data-bs-toggle": "tooltip", "data-bs-placement": "bottom", "data-bs-original-title": "いいねを取り消し" do %>
    <i class="fas fa-heart text-primary"></i>
<% end %>
<%= link_to gourmet_post_likes_path(@post), method: :post, remote: true, style: (is_liked ? "display:none;" : ""), "role": "button", "data-like-post-id": @post.id, "data-like-btn": "", "data-bs-toggle": "tooltip", "data-bs-placement": "bottom", "data-bs-original-title": "いいね" do %>
    <i class="far fa-heart text-primary"></i>
<% end %>

<script>
$(function() {
    // 多重送信対策
    $('[data-like-btn]').on('click', function(e) {
        const nowRequesting = $(this).data('now-requesting');
        if (nowRequesting) return false;
        const postId = $(this).data('like-post-id');
        $('[data-like-btn][data-like-post-id="'+postId+'"]').data('now-requesting', true);
    });
});
</script>

teamE/app/views/likes/update.js.erb
$(function() {
    // いいね数更新
    const $likeCount = $('[data-like-count][data-like-post-id="<%= j @post.id %>"]');
    $likeCount.text('<%= j number_to_human @post.likes.count, format: '%n%u', units: {thousand: 'k'} %>');

    // いいねボタンの表示切り替え
    const $likeBtns = $('[data-like-btn][data-like-post-id="<%= j @post.id %>"]');
    const $hiddenLikeBtns = $likeBtns.filter(':hidden');
    $('[data-like-btn][data-like-post-id="<%= j @post.id %>"]').hide(0);
    $likeBtns.hide(0).data('now-requesting', false);
    $hiddenLikeBtns.show(0);
});